# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, verbose_name='Название игры')),
                ('discripshion', models.TextField(blank=True, default=None, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=254, verbose_name='slug')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dev', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.Developers', verbose_name='Разработчик')),
                ('gener', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Genre', verbose_name='Жанр')),
                ('images', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.Images', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Игры',
                'verbose_name': 'Игра',
            },
        ),
    ]
