# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-07 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена'),
        ),
    ]
